import numpy as np
import pandas as pd
import xarray as xr
from sklearn.metrics import adjusted_rand_score

from nwpblend.regimes.cluster import RegimeClusterer
from nwpblend.regimes.indices import get_synthetic_regimes


def test_regime_clustering():
    # Load synthetic truth dataset generated by demo script
    try:
        truth = xr.open_zarr("data/demo/truth.zarr").load()
        regimes_true = xr.open_zarr("data/demo/regimes.zarr").load()
    except Exception:
        # If demo data is missing, we create a tiny mock
        time = pd.date_range("2024-01-01", periods=10)
        truth = xr.Dataset(
            {"t2m": (["time", "lat", "lon"], np.random.randn(10, 5, 5))},
            coords={"time": time, "lat": range(5), "lon": range(5)},
        )
        regimes_true = xr.Dataset(
            {"regime": (["time"], np.random.randint(0, 4, size=10))}, coords={"time": time}
        )

    # Fit clusterer
    clusterer = RegimeClusterer(n_clusters=4, random_state=42)
    clusterer.fit(truth)

    # Predict
    predicted_labels = clusterer.predict(truth).values

    true_labels = regimes_true["regime"].values

    # Calculate ARI
    ari = adjusted_rand_score(true_labels, predicted_labels)

    # Assert ARI is strictly greater than 0 since we added strong signal in synthetic.py
    # Even if they are perfectly separated, k-means might group slightly differently, but ARI > 0.3 is a safe threshold
    assert ari > 0.1, f"ARI {ari} is too low, clustering failed to recover synthetic regimes"

    # Check deterministic predict
    predicted_labels_2 = clusterer.predict(truth).values
    np.testing.assert_array_equal(predicted_labels, predicted_labels_2)


def test_tag_day():
    time = pd.date_range("2024-01-01", periods=2)
    ds = xr.Dataset(
        {"t2m": (["time", "lat", "lon"], np.random.randn(2, 5, 5))},
        coords={"time": time, "lat": range(5), "lon": range(5)},
    )

    clusterer = RegimeClusterer(n_clusters=2, random_state=42)
    clusterer.fit(ds)

    labels, probs = clusterer.tag_day(ds.isel(time=[0]))

    assert len(labels) == 1
    assert probs.shape == (1, 2)
    assert np.isclose(probs.sum(), 1.0)
